on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci
      - run: npm run build
      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: 15cde94dbef55da086b42d41b182e28e
          command: "pages publish --project-name='extremo-portal'  dist --branch prod"
